name 'rest-for-chef'
maintainer 'Thomas Heinen'
maintainer_email 'cochi@web.de'
issues_url 'https://github.com/cochi78/rest-for-chef/'
source_url 'https://github.com/cochi78/rest-for-chef/'
license 'Apache-2.0'
description 'Generic REST resources; PSP for NetApp ONTAP'
version '0.1.0'
chef_version '>= 17.4'
